@extends('layouts.AuthLayout')

@section('title', 'Two Factor Authintication')
@section('title', 'Security')

@section('css')
    <style>
        .imagePreview {
            height: 100px;
            width: 100px;
            margin-top: 10px;
            border: none;
        }

        .parsley-errors-list {
            list-style: none;
            padding-left: 0;
            margin: 0;
            color: red;
            font-size: 14px;
        }

        .parsley-errors-list li {
            display: inline;
        }

        .imagePreview {
            display: none;
            width: 200px;
            height: 200px;
            object-fit: contain;
            border-radius: 12px;
        }
    </style>
@endsection
@section('content')

    <div class="auth-form">
        <div class="card my-5">
            <div class="card-body">
                <div class="text-center">
                    <img src="{{ getLogo() }}" alt="images" class="img-fluid mb-3">
                    <h4 class="f-w-500 mb-3">Two Factor Authentication</h4>
                </div>
                {{-- <div class="col-12">
                    @include('layouts.message')
                </div> --}}
                <form class="authenticationForm" method="POST" action="{{ route('admin.security.authentication') }}">
                    @csrf
                    <div class="form-group mb-3">
                        <p class="mb-3">Please enter the code generated by your Authenticator App</p>
                    </div>
                    <div class="form-group mb-3">
                        <input type="number" type="number" name="otp" class="form-control" required
                            placeholder="Enter verification code"
                            data-parsley-required-message="Verification code required.">
                    </div>
                    <div class="d-grid mt-4">
                        <button type="submit" class="btn btn-primary">Confirm</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection
@section('scripts')
    <script type="module">
        $(function() {
            $('.authenticationForm').parsley();
        });
    </script>
@endsection
